const router = require("express").Router();
const { anime } = require("../controllers/anime");
const { aqua } = require("../controllers/aqua");
const { ausand } = require("../controllers/ausand");
const { caidloli } = require("../controllers/caidloli");
const { chitanda } = require("../controllers/chitanda");
const { kana } = require("../controllers/kana");
const { kurumi } = require("../controllers/kurumi");
const { loli } = require("../controllers/loli");
const { lucy } = require("../controllers/lucy");
const { mirai } = require("../controllers/mirai");
const { naughty } = require("../controllers/naughty");
const { nsfw } = require("../controllers/nsfw");
const { rem } = require("../controllers/rem");
const { sagiri } = require("../controllers/sagiri");
const { umaru } = require("../controllers/umaru");
const { cadao } = require("../controllers/cadao");
const { girl } = require("../controllers/girl");
const { home } = require("../controllers/home");

router.get("/anime", anime);
router.get("/aqua", aqua);
router.get("/ausand", ausand);
router.get("/caidloli", caidloli);
router.get("/chitanda", chitanda);
router.get("/kana", kana);
router.get("/lucy", lucy);
router.get("/mirai", mirai);
router.get("/loli", loli);
router.get("/kurumi", kurumi);
router.get("/naughty", naughty);
router.get("/nsfw", nsfw);
router.get("/rem", rem);
router.get("/sagiri", sagiri);
router.get("/umaru", umaru);
router.get("/cadao", cadao);
router.get("/girl", girl);
router.get("/", home);

module.exports = router;